language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libqt4-dev qt4-dev-tools"
  - "sudo apt-get install -qq xvfb"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "cd client && python setup.py develop && cd .."
  - "cd server/tests && qmake-qt4 && make -j4 && cd ../.."
  - "cd server && python setup.py develop && cd .."
  # use a wheel version of PySide for functiona tests
  - pip install --find-links https://parkin.github.io/python-wheelhouse/ --use-wheel PySide;
  # Travis CI servers use virtualenvs, so we need to finish the install by the following
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
# command to run tests
script:
  - "nosetests -w client/"
  - "make -C server/tests/ check"
  - "cd tests-functionnal && nosetests && cd .."
