sudo: required
cache:
  - pip
  - ccache
notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  fast_finish: true
  include:

    # Linux Qt4 Python2.7
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env: QT_SELECT=4 PYTHON=python

    # Linux Qt4 Python3.4
    - os: linux
      dist: trusty
      language: python
      python: 3.4
      env: QT_SELECT=4 PYTHON=python

    # Linux Qt5 Python2.7
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env: QT_SELECT=5 PYTHON=python

    # Linux Qt5 Python3.4
    - os: linux
      dist: trusty
      language: python
      python: 3.4
      env: QT_SELECT=5 PYTHON=python

    # MacOS Qt5 Python2
    - os: osx
      language: cpp
      env: QT_SELECT=5 PYTHON=python2

    # MacOS Qt5 Python3
    - os: osx
      language: cpp
      env: QT_SELECT=5 PYTHON=python3

install:
  - source ./ci/install_dependencies.sh # source required because of exports
  - $PYTHON --version                   # check exact python version
  - qmake --version                     # check exact Qt version

script:
  - flake8 client/funq server/funq_server
  - cd client && $PYTHON setup.py develop && cd ..
  - cd server && $PYTHON setup.py develop && cd ..
  - cd server/tests && qmake && make -j4 && cd ../..
  - cd client && $PYTHON setup.py test; cd ..
  - make -C server/tests/ check
  # PySide is Qt4, so we can't run functional tests with Qt5!
  - if [[ "$QT_SELECT" == "4" ]]; then cd tests-functionnal && nosetests && cd .. ; fi
