language: python
cache: pip
python:
  - "2.7"
  - "3.4"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libqt4-dev qt4-dev-tools"
  - "sudo apt-get install -qq xvfb"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install flake8; fi"
  - "cd client && python setup.py develop && cd .."
  - "cd server/tests && qmake-qt4 && make -j4 && cd ../.."
  - "cd server && python setup.py develop && cd .."
  - pip install PySide
# command to run tests
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 client/funq server/funq_server; fi"
  - "cd client && python setup.py test; cd .."
  - "make -C server/tests/ check"
  - "cd tests-functionnal && nosetests && cd .."
