language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libqt4-dev qt4-dev-tools"
  - "sudo apt-get install -qq xvfb"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "cd client && python setup.py develop && cd .."
  - "cd server/tests && qmake-qt4 && make -j4 && cd ../.."
# command to run tests
script:
  - "nosetests -w client/"
  - "make -C server/tests/ check"
