os: Windows Server 2012
build: off
test: off
deploy: off

init:
  - set PATH=C:/Qt/5.9/mingw53_32/bin;C:/Qt/Tools/mingw530_32/bin;%PATH%

install:
  - cp C:/Qt/Tools/mingw530_32/bin/mingw32-make.exe C:/Qt/Tools/mingw530_32/bin/make.exe
  - cd client && python setup.py develop && cd ..
  - cd server && python setup.py develop && cd ..
  - cd server/tests && qmake && make -j4 && cd ../../
  - pip install PySide

build_script:
  - cd client && python setup.py test && cd ..
# TODO:  - make -C server/tests/ check
# TODO:  - cd tests-functionnal && nosetests
